<?php

/**
 * @copyright   Léandro Tijink
 * @license     MIT
 */

namespace App;

enum GuardType: string
{
	case App = 'app';
	case Email = 'email';
	case Recovery = 'recovery';

	// -----------------

	public function icon(): string
	{
		return match ($this) {
			GuardType::App => icon('media.qr-code'),
			GuardType::Email => icon('email.envelope-email'),
			GuardType::Recovery => icon('learning.briefcase-medical'),
		};
	}

	public function label(): string
	{
		return match ($this) {
			GuardType::App => 'Authenticator app',
			GuardType::Email => 'Email',
			GuardType::Recovery => 'Recovery codes',
		};
	}

	public function description(): string
	{
		return match ($this) {
			GuardType::App => 'Verify each sign-in using a code generated by a supporting app.',
			GuardType::Email => 'Receive an email with a code to verify each sign-in.',
			GuardType::Recovery => 'You can recover your account using one of the pre-generated codes.',
		};
	}
}